### ISSUE TITLE
Monkeypatching may pose a couple problems

### ISSUE THREAD

**Issue by exodist** [yanick/Test-Some#1]
The module modifies &Test::More::subtest in-place. It does so in what is probably the safest way possible, but it still may be undesired. This will effect scopes that use Test::More without importing Test::Some. This may be desired in many cases, but should probably not be a default.

The module could instead wrap the sub in the importing namespace instead of wrapping the one in Test::More. This would prevent it from effecting unexpected places. It would also play nicer with other modules that do similar things. As it stands this also would cause a problem if I or other Test::More maintainers decided to change things under the hood and not have a 'subtest' function directly, but maybe generate importer-specific subtest functions. (I do not intend to do this, I am just stating possibilities)

**Comment by yanick** [comment]
Yeah, I thought long about that one. The use-case that speaks for the monkeypatching is:

   perl -MTest::Some=that_one t/some_test.t

In that case, the loading of `Test::Some` comes before `Test::More`, so anything we do for `subtest` in the current namespace is going to be overriden by `Test::More`.

Hmmm... Unless I preemptively call in 'Test::More' and make sure that `subtest` is already there.... Oh yeah. 

I realize this last paragraph makes little sense. But I think I know what to do. Thanks. ^.^

**Comment by exodist** [comment]
Couple concerns:

1) Loading Test::More for them seems like overkill, maybe just die if it looks like subtest() is not in the callers namespace, with a helpful message saying Test::More needs to be loaded first?

2) Your string eval pretends to be in the callers package, but does not alter the line number or file. If someone used this and Class::Method::Modifiers was not installed then the require error will report inside an eval and be very confusing.

This would be a good way to make the errors in your string eval sane, the comment is not a true comment, it makes perl think it is in that line and file+extra little note
```perl
eval <<EOT
#line 55 "filename (inside Test::Some)"
use Test::More; use Class::Method::Modifiers; around ...;
EOT
```

3) Loading Class::Method::Modifier into their namespace for them could also potentially cause problems.

I would suggest simplifying this:

```perl
sub import {
    my $class = shift;
    my $caller = caller;
    my $subtest = $caller->can('subtest') or croak "Test::More must be loaded before Test::Some";
    no warnings 'redefine';
    no strict 'refs';
    *{"$caller\::subtest"} = sub { Test::Some::_subtest( \@_, $subtest ) };
}
```

This is shorter, and does nto contaminate their namespace. It also passes in their current subtest subref so that your subtest code can defer to it instead of assuming they just have Test::More's, which means you can wrap subtest from other tools, and support other tools that also wrap subtest.

**Comment by yanick** [comment]
Very good points. Moved to #4 :-)  Thanks!
